version: 0.2

phases:
  install:
   runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - docker --version
      - docker images
      - git --version
      - make --version
      - pwd
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install terraform
      - echo Use Python 3.7.10 ...
      - echo "3.7.10" > ./.python-version
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the redash code
      - python --version
      - pwd
      - ls
      - echo Set environment variables ...
      - echo "REDASH_LOG_LEVEL=$REDASH_LOG_LEVEL" > ./.env
      - echo "REDASH_COOKIE_SECRET=$REDASH_COOKIE_SECRET" >> ./.env
      - echo "REDASH_REDIS_URL=$REDASH_REDIS_URL" >> ./.env
      - echo "REDASH_DATABASE_URL=$REDASH_DATABASE_URL" >> ./.env
      - echo Build Docker image ...
      - docker build -t $ECR_REPO:$IMAGE_TAG -f Dockerfile .
      - echo Initialize database schema ...
      - docker run --env-file .env $ECR_REPO:$IMAGE_TAG create_db
      - echo Tag Docker image ...
      - docker tag $ECR_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr describe-repositories --repository-names ${ECR_REPO} || aws ecr create-repository --repository-name ${ECR_REPO}
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - terraform -chdir=deployments/tf/dev init
      - terraform -chdir=deployments/tf/dev plan -var client=$CLIENT -var team=$TEAM -var image_tag=$IMAGE_TAG -var doppler_token=$DOPPLER_TOKEN

