version: 0.2

phases:
  install:
   runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - docker --version
      - docker images
      - git --version
      - make --version
      - pwd
      - echo Use Python 3.7.10 ...
      - echo "3.7.10" > ./.python-version
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the redash code
      - python --version
      - pwd
      - ls
      - echo Build Docker image ...
      - docker build -t $ECR_REPO:$IMAGE_TAG -f Dockerfile .
      - echo Initialize database schema ...
      - docker run $ECR_REPO:$IMAGE_TAG create_db
      - echo Tag Docker image ...
      - docker tag $ECR_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr describe-repositories --repository-names ${ECR_REPO} || aws ecr create-repository --repository-name ${ECR_REPO}
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

