name: Docker Image CI

on:
  push:
    branches:
      - master
      - qa
      - production
jobs:
  validate:
    uses: "$GITHUB_REPOSITORY/.github/workflows/check.yml@$GITHUB_SHA"

  build:
    runs-on: ubuntu-latest
    needs: [validate]
    env:
      ECR_REPO: usedata.io/redash
      IMAGE_TAG: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      id: docker-build
      run: docker build . --file Dockerfile --tag "$ECR_REPO:$IMAGE_TAG"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
#        role-session-name: RedashGitHubActions
#        role-skip-session-tagging: true
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Create ECR repository if not exist
      run: |
        aws ecr describe-repositories --repository-names ${ECR_REPO} || aws ecr create-repository --repository-name ${ECR_REPO}
    - name: Push Docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker tag $ECR_REPO:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
